name: account_app
description: "语音记账App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # 状态管理
  flutter_riverpod: 2.6.1
  riverpod_annotation: 2.6.1

  # 路由
  go_router: 14.8.0

  # 本地数据库
  sqflite: 2.4.2

  # 本地存储
  shared_preferences: 2.5.2

  # 网络请求
  dio: 5.8.0+1

  # 日期处理
  intl: 0.20.2

  # 语音录制
  record: ^6.0.0

  # 图表
  fl_chart: 0.70.2

  # 路径
  path_provider: 2.1.5
  path: 1.9.1

  # 桌面小组件
  home_widget: 0.7.0

  # 图片选择
  image_picker: ^1.1.2

  # 权限
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

  riverpod_generator: 2.6.4
  build_runner: 2.4.14

flutter:
  uses-material-design: true
